<?php

/**
 * Implements hook_views_api().
 */
function bootstrap_wookmark_views_api() {
    if (($library = libraries_load('wookmark')) && !empty($library['loaded'])) {
      drupal_add_js(drupal_get_path('module', 'bootstrap_wookmark') . '/js/active.js');
    }

  return array(
    'api' => '3'
  );
}

/**
 * Implements hook_libraries_info().
 */
function bootstrap_wookmark_libraries_info() {
  $libraries['wookmark'] = array(
    'name' => 'wookmark',
    'vendor url' => 'http://www.wookmark.com/jquery-plugin',
    'download url' => 'https://github.com/germanysbestkeptsecret/Wookmark-jQuery',
    'version' => '2.1.2',
    'files' => array(
      'js' => array(
        'jquery.wookmark.js',
      ),
    ),
    'variant' => array(
      'minified' => array(
        'files' => array(
          'js' => array(
            'jquery.wookmark.min.js',
          )
        ),
      ),
    ),
  );
  return $libraries;
}
